# Generated by Django 4.2.16 on 2026-07-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_expense_is_paid_expense_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='employee_code',
            field=models.CharField(blank=True, help_text='Optional Employee Code for this expense', max_length=50, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='expense',
                    name='gst_amount',
                    field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                migrations.AddField(
                    model_name='expense',
                    name='payload',
                    field=models.JSONField(blank=True, default=dict, null=True),
                ),
                migrations.AlterField(
                    model_name='expense',
                    name='expense_type',
                    field=models.CharField(choices=[('Daily Expenses', (('Petrol and Diesel', 'Petrol and Diesel'), ('Travel', 'Travel'), ('Hotel', 'Hotel'), ('Food Expenses', 'Food Expenses'), ('Office stationary', 'Office stationary'), ('Courier expenses', 'Courier expenses'), ('Transportation Payment', 'Transportation Payment'), ('Marketing Expenses', 'Marketing Expenses'), ('Customer Delight', 'Customer Delight'), ('Other Daily', 'Other'))), ('Fixed Cost', (('Staff salary', 'Staff salary'), ('OFC rent', 'OFC rent'), ('Electricity bill', 'Electricity bill'), ('Internet Bill', 'Internet Bill'), ('Google workspace', 'Google workspace'), ('Website and hosting cost', 'Website and hosting cost'), ('Other Fixed', 'Other')))], max_length=50),
                ),
            ],
            database_operations=[],
        ),
    ]
