# Generated by Django 4.2.16 on 2026-07-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_expense_employee_code_expense_gst_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(max_length=100),
        ),
    ]
