# Generated by Django 4.2.16 on 2026-08-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_expense_expense_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['date'], name='payments_pa_date_f2f1ad_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['contact', 'date'], name='payments_pa_contact_197952_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['document_ref'], name='payments_pa_documen_0fc766_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_mode'], name='payments_pa_payment_949f98_idx'),
        ),
    ]
