# Generated by Antigravity for Expense clarification workflow

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0006_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(
                choices=[
                    ('Pending', 'Pending'),
                    ('Clarification', 'Needs Clarification'),
                    ('Clarification Provided', 'Clarification Provided'),
                    ('Approved', 'Approved'),
                    ('Rejected', 'Rejected'),
                ],
                default='Pending',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='expense',
            name='clarification_query',
            field=models.TextField(blank=True, help_text='Admin query on missing or incorrect information', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='clarification_response',
            field=models.TextField(blank=True, help_text="User's explanation or response", null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='clarification_raised_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='clarifications_raised',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='expense',
            name='clarification_raised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='clarification_popup_seen',
            field=models.BooleanField(
                default=True,
                help_text='Set to False when admin raises clarification; True when user views/acknowledges',
            ),
        ),
    ]
