# Generated by Django 5.2.14 on 2026-05-26 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_tax_validators'),
        ('inventory', '0002_product_selling_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quoted_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quote_date', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('lead_time_days', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_quotes', to='inventory.product')),
                ('vendor', models.ForeignKey(limit_choices_to={'contact_type__in': ['Vendor', 'Both']}, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_quotes', to='contacts.contact')),
            ],
            options={
                'ordering': ['quoted_price'],
            },
        ),
    ]
