# Generated by Django 5.2.14 on 2026-06-27 13:15

from django.db import migrations


def migrate_address_data(apps, schema_editor):
    Address = apps.get_model('contacts', 'Address')
    for address in Address.objects.all():
        parts = []
        if address.street: parts.append(address.street)
        if address.city: parts.append(address.city)
        state_postal = []
        if address.state: state_postal.append(address.state)
        if address.postal_code: state_postal.append(address.postal_code)
        if state_postal: parts.append("-".join(state_postal))
        if address.country: parts.append(address.country)
        
        address.address = "\n".join(parts)
        address.save()

class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_address_address_alter_address_city_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_address_data, reverse_code=migrations.RunPython.noop),
    ]
