# Generated by Django 4.2.16 on 2026-07-11 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_remove_address_city_remove_address_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
