# Generated by Django 4.2.16 on 2026-08-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_address_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['name'], name='contacts_co_name_6f3a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['gstin'], name='contacts_co_gstin_583b2d_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['phone'], name='contacts_co_phone_5a60c7_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['contact_type'], name='contacts_co_contact_d678b6_idx'),
        ),
    ]
