# Generated by Django 5.2.14 on 2026-05-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_onboarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_onboarded',
            field=models.BooleanField(default=True),
        ),
    ]
