# Generated by Django 4.2.16 on 2026-07-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_otptoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Managing Director', 'Managing Director'), ('Director', 'Director'), ('Admin', 'Admin'), ('Purchase', 'Purchase'), ('Accounts', 'Accounts'), ('Tender', 'Tender'), ('HR', 'HR'), ('Engineering', 'Engineering'), ('Project', 'Project'), ('Viewer', 'Viewer'), ('Accountant', 'Accountant'), ('Staff', 'Staff')], default='Staff', max_length=30),
        ),
    ]
