# Generated by Django 4.2.16 on 2026-07-31 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_expand_role_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSectionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('DASHBOARD', 'Dashboard'), ('USERS', 'User Management'), ('CONTACTS', 'Contacts (Clients/Vendors)'), ('INVENTORY', 'Inventory & Warranty'), ('EDMS', 'Document Management (EDMS)'), ('PAYMENTS', 'Payments & Expenses'), ('REPORTING', 'Reporting'), ('TRACKER', 'Manufacturing Tracker'), ('DOCUMENTS', 'Invoices & Estimates')], max_length=50)),
                ('can_read', models.BooleanField(default=False)),
                ('can_write', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Section Permission',
                'verbose_name_plural': 'Section Permissions',
                'unique_together': {('user', 'section')},
            },
        ),
    ]
