# Generated by Django 4.2.16 on 2026-09-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usersectionpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersectionpermission',
            name='section',
            field=models.CharField(choices=[('DASHBOARD', 'Dashboard'), ('USERS', 'User Management'), ('CONTACTS', 'Contacts (Clients/Vendors)'), ('INVENTORY', 'Inventory & Warranty'), ('EDMS', 'Document Management (EDMS)'), ('PAYMENTS', 'Payments & Expenses'), ('REPORTING', 'Reporting'), ('TRACKER', 'Manufacturing Tracker'), ('DOCUMENTS', 'Invoices & Estimates'), ('HR_ATTENDANCE', 'HR & Attendance')], max_length=50),
        ),
    ]
