# Generated by Django 4.2.16 on 2026-07-06 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import edms.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EDMSCompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('cin', models.CharField(blank=True, max_length=30, verbose_name='CIN')),
                ('udyam_number', models.CharField(blank=True, max_length=30)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('iso_number', models.CharField(blank=True, max_length=50, verbose_name='ISO Number')),
                ('financial_year', models.CharField(blank=True, help_text='e.g. 2025-26', max_length=10)),
                ('turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='edms_company/')),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
            },
        ),
        migrations.CreateModel(
            name='EDMSDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('certificate', 'Certificate'), ('legal', 'Legal'), ('financial', 'Financial'), ('hr', 'HR'), ('purchase', 'Purchase'), ('tender', 'Tender'), ('vendor', 'Vendor'), ('project', 'Project'), ('policy', 'Policy/SOP'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('keywords', models.TextField(blank=True, help_text='Space or comma separated keywords for search')),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('department', 'Department Only'), ('management', 'Management'), ('admin', 'Admin Only')], db_index=True, default='internal', max_length=20)),
                ('is_confidential', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('po_number', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='PO Number')),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('bill_number', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('payment_status', models.CharField(blank=True, choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid')], max_length=30)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('file_extension', models.CharField(blank=True, db_index=True, max_length=20)),
                ('file_hash', models.CharField(blank=True, db_index=True, help_text='SHA-256 hex digest of latest version', max_length=64)),
                ('ocr_text', models.TextField(blank=True, help_text='OCR-extracted text (future feature)')),
                ('ocr_processed', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('delete_reason', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_edms_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'EDMS Document',
                'verbose_name_plural': 'EDMS Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EDMSDocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EDMSVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gst_number', models.CharField(blank=True, max_length=20, verbose_name='GST')),
                ('pan_number', models.CharField(blank=True, max_length=20, verbose_name='PAN')),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EDMSNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edms.edmsdocument')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edms_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EDMSDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(max_length=500, upload_to=edms.models._edms_upload_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(help_text='Size in bytes')),
                ('mime_type', models.CharField(max_length=120)),
                ('file_extension', models.CharField(max_length=20)),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 hex digest', max_length=64)),
                ('change_note', models.CharField(blank=True, help_text='Brief description of changes in this version', max_length=255)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='edms.edmsdocument')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Version',
                'verbose_name_plural': 'Document Versions',
                'ordering': ['-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='EDMSDocumentDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='edms.edmsdocument')),
                ('downloaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edms_downloads', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='edms.edmsdocumentversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EDMSDocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='📄', max_length=50)),
                ('color', models.CharField(blank=True, default='#6366f1', help_text='Hex colour for UI badge', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='System-created default category')),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='edms.edmsdocumentcategory')),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EDMSDocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, help_text='Role name (if granting to all users of that role)', max_length=30)),
                ('permission', models.CharField(choices=[('view', 'View'), ('preview', 'Preview'), ('download', 'Download'), ('edit_metadata', 'Edit Metadata'), ('delete', 'Delete'), ('approve', 'Approve'), ('restore', 'Restore'), ('share', 'Share'), ('export', 'Export')], max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='edms.edmsdocument')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edms_access_grants_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edms_access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Access Grant',
                'verbose_name_plural': 'Document Access Grants',
            },
        ),
        migrations.AddField(
            model_name='edmsdocument',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='edms.edmsdocumentcategory'),
        ),
        migrations.AddField(
            model_name='edmsdocument',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='edms.edmscompanyprofile'),
        ),
        migrations.AddField(
            model_name='edmsdocument',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_edms_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='edmsdocument',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='edms.department'),
        ),
        migrations.AddField(
            model_name='edmsdocument',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_edms_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='edmsdocument',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='edms.edmsdocumenttag'),
        ),
        migrations.AddField(
            model_name='edmsdocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_edms_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='edmsdocument',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='edms.edmsvendor'),
        ),
        migrations.CreateModel(
            name='EDMSAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_cached', models.CharField(blank=True, help_text='Stored at log time in case user is later deleted', max_length=150)),
                ('user_role', models.CharField(blank=True, max_length=30)),
                ('department_name', models.CharField(blank=True, max_length=100)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('upload', 'Upload'), ('preview', 'Preview'), ('download', 'Download'), ('delete', 'Delete'), ('restore', 'Restore'), ('edit', 'Edit Metadata'), ('approve', 'Approve'), ('reject', 'Reject'), ('share', 'Share'), ('permission_change', 'Permission Change'), ('failed_access', 'Failed Access'), ('search', 'Search'), ('export', 'Export'), ('version_create', 'Version Created')], db_index=True, max_length=30)),
                ('document_title', models.CharField(blank=True, help_text='Cached at log time', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('success', models.BooleanField(default=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='edms.edmsdocument')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edms_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EDMSSavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('filters', models.JSONField(default=dict, help_text='Serialised query-string filters')),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edms_saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='edmsdocument',
            index=models.Index(fields=['category', 'is_deleted'], name='edms_edmsdo_categor_d38d37_idx'),
        ),
        migrations.AddIndex(
            model_name='edmsdocument',
            index=models.Index(fields=['department', 'is_deleted'], name='edms_edmsdo_departm_02af65_idx'),
        ),
        migrations.AddIndex(
            model_name='edmsdocument',
            index=models.Index(fields=['approval_status', 'is_deleted'], name='edms_edmsdo_approva_ae82c5_idx'),
        ),
        migrations.AddIndex(
            model_name='edmsdocument',
            index=models.Index(fields=['expiry_date'], name='edms_edmsdo_expiry__ef16db_idx'),
        ),
        migrations.AddIndex(
            model_name='edmsdocument',
            index=models.Index(fields=['file_hash'], name='edms_edmsdo_file_ha_7acf60_idx'),
        ),
        migrations.AddIndex(
            model_name='edmsauditlog',
            index=models.Index(fields=['action', 'timestamp'], name='edms_edmsau_action_b661f8_idx'),
        ),
        migrations.AddIndex(
            model_name='edmsauditlog',
            index=models.Index(fields=['user', 'timestamp'], name='edms_edmsau_user_id_89caa2_idx'),
        ),
    ]
