# Generated by Django 4.2.16 on 2026-07-08 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_document_force_igst'),
        ('edms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edmsdocument',
            name='commercial_doc',
            field=models.OneToOneField(blank=True, help_text='Auto-populated when synced from the commercial documents module', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edms_record', to='documents.document', verbose_name='Commercial Document'),
        ),
        migrations.AddField(
            model_name='edmsdocument',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manually Uploaded'), ('commercial', 'Auto-synced from Commercial Documents')], db_index=True, default='manual', max_length=20),
        ),
    ]
