# Generated by Django 4.2.16 on 2026-08-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0002_edmsdocument_commercial_doc_edmsdocument_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='edmsdocument',
            name='party_name',
            field=models.CharField(blank=True, db_index=True, help_text='Counter-party / client / vendor name (free text)', max_length=255, verbose_name='Party Name'),
        ),
    ]
