# Generated by Django 4.2.16 on 2026-09-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edms', '0005_edmsdocument_document_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edmsdocument',
            name='currency',
            field=models.CharField(blank=True, default='INR', max_length=10),
        ),
    ]
