import os
from django.apps import AppConfig


class DocumentsConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'documents'

    def ready(self):
        # Register EDMS auto-sync signals for commercial documents
        import documents.signals  # noqa: F401

        # Only trigger this pre-import on startup of the main server process
        # to avoid double execution under development reloader
        if os.environ.get('RUN_MAIN') == 'true' or not os.environ.get('DJANGO_SETTINGS_MODULE'):
                # Temporarily redirect raw C-level stderr descriptor (fd 2) to devnull
                # to hide UWP registry warnings generated by GLib-GIO on Windows
                devnull = os.open(os.devnull, os.O_WRONLY)
                try:
                    old_stderr = os.dup(2)
                except OSError:
                    old_stderr = None

                try:
                    if old_stderr is not None:
                        os.dup2(devnull, 2)
                    import weasyprint
                finally:
                    if old_stderr is not None:
                        os.dup2(old_stderr, 2)
                        os.close(old_stderr)
                    os.close(devnull)

