# Generated by Django 4.2.16 on 2026-08-10 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_id', models.PositiveIntegerField()),
                ('target_id', models.PositiveIntegerField()),
                ('link_type', models.CharField(choices=[('related', 'Related To'), ('converted', 'Converted To/From'), ('payment', 'Payment Proof'), ('supporting', 'Supporting Document')], default='related', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='contenttypes.contenttype')),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_links', to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['source_type', 'source_id'], name='core_docume_source__e5460b_idx'), models.Index(fields=['target_type', 'target_id'], name='core_docume_target__f9e35e_idx')],
                'unique_together': {('source_type', 'source_id', 'target_type', 'target_id', 'link_type')},
            },
        ),
    ]
