# Generated by Django 4.2.16 on 2026-08-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_documentlink_source_id_target_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemactivitylog',
            name='path',
            field=models.TextField(db_index=True),
        ),
    ]
