# Generated by Django 4.2.16 on 2026-09-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_path_index_to_activity_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlink',
            name='link_type',
            field=models.CharField(choices=[('related', 'Related To'), ('converted', 'Converted To/From'), ('payment', 'Payment Proof'), ('supporting', 'Supporting Document'), ('excluded', 'Excluded / Unlinked')], default='related', max_length=20),
        ),
    ]
