# Generated by Django on 2026-09-08
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def populate_default_leave_types(apps, schema_editor):
    LeaveType = apps.get_model('hr', 'LeaveType')
    default_types = [
        {
            'name': 'Casual Leave',
            'code': 'CL',
            'default_days': 12,
            'is_paid': True,
            'requires_approval': True,
            'carry_forward': False,
            'color': '#3b82f6',
        },
        {
            'name': 'Sick / Medical Leave',
            'code': 'SL',
            'default_days': 10,
            'is_paid': True,
            'requires_approval': True,
            'carry_forward': False,
            'color': '#10b981',
        },
        {
            'name': 'Earned Leave',
            'code': 'EL',
            'default_days': 15,
            'is_paid': True,
            'requires_approval': True,
            'carry_forward': True,
            'max_carry_forward_days': 30,
            'color': '#8b5cf6',
        },
        {
            'name': 'Loss of Pay',
            'code': 'LOP',
            'default_days': 0,
            'is_paid': False,
            'requires_approval': True,
            'carry_forward': False,
            'color': '#ef4444',
        },
    ]
    for lt in default_types:
        LeaveType.objects.get_or_create(code=lt['code'], defaults=lt)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='E.g. Casual Leave, Medical Leave', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code, e.g. CL, EL, ML', max_length=10, unique=True)),
                ('default_days', models.PositiveSmallIntegerField(default=0, help_text='Default annual allocation (0 = unlimited / LOP)')),
                ('is_paid', models.BooleanField(default=True, help_text='Is this a paid leave?')),
                ('requires_approval', models.BooleanField(default=True)),
                ('carry_forward', models.BooleanField(default=False, help_text='Unused days roll over to next year')),
                ('max_carry_forward_days', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#6366f1', help_text='Badge colour (hex)', max_length=20)),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('is_optional', models.BooleanField(default=False, help_text='Optional/restricted holiday')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('session', models.CharField(choices=[('FULL', 'Full Day'), ('FIRST_HALF', 'First Half'), ('SECOND_HALF', 'Second Half')], default='FULL', max_length=20)),
                ('days_count', models.DecimalField(decimal_places=1, default=0, help_text='Auto-calculated working days', max_digits=5)),
                ('reason', models.TextField(help_text='Reason for leave')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_note', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='hr/leave_attachments/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='hr.leavetype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'ordering': ['-from_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(help_text='Calendar year, e.g. 2026')),
                ('days_allocated', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('days_carried_forward', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_allocations_created', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hr.leavetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Allocation',
                'ordering': ['-year', 'user__first_name'],
                'unique_together': {('user', 'leave_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('WFH', 'Work From Home'), ('ON_LEAVE', 'On Leave'), ('HOLIDAY', 'Holiday'), ('WEEKLY_OFF', 'Weekly Off')], db_index=True, default='PRESENT', max_length=20)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('leave_request', models.ForeignKey(blank=True, help_text='Linked leave request if status=ON_LEAVE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='hr.leaverequest')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', 'employee__first_name'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.RunPython(populate_default_leave_types, migrations.RunPython.noop),
    ]
