# Generated by Django 4.2.16 on 2026-07-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Set to the first day of the month', unique=True)),
                ('target_sales_orders', models.IntegerField(default=0)),
                ('actual_sales_orders', models.IntegerField(default=0)),
                ('target_sales_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('actual_sales_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('target_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('actual_profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sales_payments_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('target_purchase_orders', models.IntegerField(default=0)),
                ('actual_purchase_orders', models.IntegerField(default=0)),
                ('target_purchase_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('actual_purchase_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('purchase_payments_given', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
    ]
