# Generated by Django 4.2.16 on 2026-07-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('payments_received', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('expected_month', models.DateField(help_text='Set to the first day of the month it is planned for')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_month', models.DateField(blank=True, help_text='The month it was actually completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlannedPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('payments_given', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('expected_month', models.DateField(help_text='Set to the first day of the month it is planned for')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_month', models.DateField(blank=True, help_text='The month it was actually completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MonthlyPlan',
        ),
    ]
