# Generated by Django 4.2.16 on 2026-07-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_plannedorder_plannedpurchase_delete_monthlyplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannedorder',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='plannedpurchase',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='plannedorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='plannedpurchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
