# Generated by Django 4.2.16 on 2026-07-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_remove_plannedorder_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedorder',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='plannedpurchase',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
