# Generated by Django 4.2.16 on 2026-09-23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0039_document_skip_reminder'),
        ('reporting', '0004_alter_plannedorder_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('party', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('reminder_type', models.CharField(choices=[('receivable', 'Receivable'), ('payable', 'Payable')], default='receivable', max_length=20)),
                ('is_urgent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_reminders', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminders', to='documents.document')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
            },
        ),
    ]
