# Generated by Django 4.2.16 on 2026-06-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_purchase_price_product_reorder_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warranty_months',
            field=models.IntegerField(default=12, help_text='Default warranty period in months'),
        ),
    ]
