# Generated by Django 4.2.16 on 2026-07-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_warrantyregistration_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantyclaim',
            name='status_reason',
            field=models.TextField(blank=True, help_text='Reason for the current status', null=True),
        ),
    ]
