# Generated by Django 5.2.14 on 2026-05-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
