# Generated by Django 5.2.14 on 2026-05-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='show_gst',
            field=models.BooleanField(default=False),
        ),
    ]
