# Generated by Django 5.2.14 on 2026-05-22 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_show_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='split_gst',
            field=models.BooleanField(default=False),
        ),
    ]
