# Generated by Django 4.2.16 on 2026-05-25 14:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_split_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='discount_type',
            field=models.CharField(choices=[('none', 'No Discount'), ('fixed', 'Global Fixed'), ('percentage', 'Global Percentage'), ('individual', 'Individual Discount')], default='none', max_length=15),
        ),
        migrations.AddField(
            model_name='document',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
