# Generated by Django 5.2.14 on 2026-05-26 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_discount_type_document_discount_value'),
    ]

    operations = [
    ]
