# Generated by Django 4.2.16 on 2026-05-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_tender'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='payment_milestones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
