# Generated by Django 4.2.16 on 2026-05-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_payment_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='numbering_mode',
            field=models.CharField(default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='documentitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
