# Generated by Django on 2026-05-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_document_numbering_mode_documentitem_hsn_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='tender_ref',
        ),
    ]
