# Generated by Django 4.2.16 on 2026-06-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_remove_tender_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentitem',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
