# Generated by Django 4.2.16 on 2026-06-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_documentitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='discount_type',
            field=models.CharField(choices=[('none', 'No Discount'), ('fixed', 'Global Fixed'), ('percentage', 'Global Percentage'), ('individual', 'Individual (₹)'), ('individual_pct', 'Individual (%)')], default='none', max_length=15),
        ),
    ]
