# Generated by Django 5.2.14 on 2026-06-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_alter_document_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='table_columns',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentitem',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
