# Generated by Django 4.2.16 on 2026-06-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_document_table_columns_documentitem_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='po_date',
            field=models.DateField(blank=True, null=True, verbose_name='PO Reference Date'),
        ),
        migrations.AddField(
            model_name='document',
            name='po_reference_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='PO Reference Number'),
        ),
    ]
