# Generated by Django 5.2.14 on 2026-06-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_document_po_date_document_po_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='place_of_supply',
            field=models.CharField(blank=True, default='21-Odisha', max_length=100, null=True, verbose_name='Place of Supply'),
        ),
    ]
