# Generated by Django 4.2.16 on 2026-06-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_document_place_of_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentitem',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial Number'),
        ),
    ]
