# Generated by Django 5.2.14 on 2026-07-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_documentitem_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentitem',
            name='has_warranty',
            field=models.BooleanField(default=True),
        ),
    ]
