# Generated by Django 5.2.14 on 2026-07-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_documentitem_has_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentitem',
            name='has_warranty',
            field=models.BooleanField(default=False),
        ),
    ]
