# Generated by Django 5.2.14 on 2026-07-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_alter_documentitem_has_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='enable_warranty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentitem',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentitem',
            name='warranty_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
