# Generated by Django 5.2.14 on 2026-07-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_document_enable_warranty_documentitem_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
