# Generated by Django 5.2.14 on 2026-07-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_document_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentitem',
            name='warranty_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
