# Generated by Django 4.2.16 on 2026-07-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_documentitem_warranty_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='repeat_header',
            field=models.BooleanField(default=False),
        ),
    ]
