# Generated by Django 4.2.16 on 2026-07-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_document_repeat_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentitem',
            name='serial_number',
            field=models.TextField(blank=True, null=True, verbose_name='Serial Number'),
        ),
    ]
