# Generated by Django 4.2.16 on 2026-07-02 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_alter_documentitem_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
