# Generated by Django 4.2.16 on 2026-07-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_alter_document_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='force_igst',
            field=models.BooleanField(default=False),
        ),
    ]
