# Generated by Django 4.2.16 on 2026-07-09 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_document_force_igst'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_documents', to='documents.document'),
        ),
    ]
