# Generated by Django 4.2.16 on 2026-07-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0026_document_source_document'),
    ]

    operations = [

        migrations.AddField(
            model_name='document',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shipping Name'),
        ),

        migrations.AlterField(
            model_name='document',
            name='eway_bill',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='E-Way Bill No.'),
        ),
    ]
