# Generated by Django 4.2.16 on 2026-08-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0027_document_eway_bill_date_document_shipping_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='eway_bill_date',
            field=models.DateField(blank=True, null=True, verbose_name='E-Way Bill Date'),
        ),
        migrations.AddField(
            model_name='document',
            name='transport_doc_date',
            field=models.DateField(blank=True, null=True, verbose_name='Transporter Doc Date'),
        ),
        migrations.AddField(
            model_name='document',
            name='transport_doc_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transporter Doc No.'),
        ),
        migrations.AddField(
            model_name='document',
            name='transport_reason',
            field=models.TextField(blank=True, default='Refilling only, No Commercial involvement.', null=True, verbose_name='Transport Reason'),
        ),
        migrations.AddField(
            model_name='document',
            name='transporter_details',
            field=models.CharField(blank=True, default='Local Transportation', max_length=255, null=True, verbose_name='Transporter Details'),
        ),
        migrations.AddField(
            model_name='document',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transporter Vehicle No.'),
        ),
    ]
