# Generated by Django 4.2.16 on 2026-08-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_document_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='bill_from_address',
            field=models.TextField(blank=True, null=True, verbose_name='Bill From Address'),
        ),
        migrations.AddField(
            model_name='document',
            name='bill_from_gstin',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Bill From GSTIN'),
        ),
        migrations.AddField(
            model_name='document',
            name='bill_from_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bill From Name'),
        ),
        migrations.AddField(
            model_name='document',
            name='ship_from_address',
            field=models.TextField(blank=True, null=True, verbose_name='Ship From Address / Warehouse'),
        ),
        migrations.AddField(
            model_name='document',
            name='ship_from_gstin',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Ship From GSTIN'),
        ),
        migrations.AddField(
            model_name='document',
            name='ship_from_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ship From Name / Dispatch Location'),
        ),
    ]
