# Generated by Django 4.2.16 on 2026-08-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_document_bill_from_address_document_bill_from_gstin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['number'], name='documents_d_number_3bd291_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['type', 'date'], name='documents_d_type_65257b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['contact', 'date'], name='documents_d_contact_fd2f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
    ]
