# Generated by Django 4.2.16 on 2026-09-22 09:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0037_document_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=12, verbose_name='Exchange Rate to INR'),
        ),
    ]
