# Generated by Django 5.2.14 on 2026-05-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='ODtech Solutions', max_length=255)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('pan', models.CharField(blank=True, max_length=10, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('terms_conditions', models.TextField(blank=True, null=True)),
                ('invoice_prefix', models.CharField(default='INV-', max_length=10)),
                ('quotation_prefix', models.CharField(default='QTN-', max_length=10)),
                ('po_prefix', models.CharField(default='PO-', max_length=10)),
                ('challan_prefix', models.CharField(default='CHL-', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
