# Generated by Django 4.2.16 on 2026-07-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_remove_companydocument_category_documentfolder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='doc_number_format',
            field=models.CharField(choices=[('OD-{FY}-{MM}-{N}', 'OD-26-07-285  (FY + Month + S.No.)'), ('OD-{TYPE}-{FY}-{MM}-{N}', 'OD-INV-26-07-285  (Type + FY + Month + S.No.)'), ('OD-{TYPE}-{FYFY}-{MM}-{N}', 'OD-INV-2627-07-285  (Type + Full FY + Month + S.No.)')], default='OD-{FY}-{MM}-{N}', max_length=40),
        ),
    ]
