# Generated by Django 4.2.16 on 2026-07-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_companyprofile_allow_document_deletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='seq_chl',
            field=models.IntegerField(default=0, verbose_name='Last Delivery Challan Sequence'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='seq_crn',
            field=models.IntegerField(default=0, verbose_name='Last Credit Note Sequence'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='seq_dbn',
            field=models.IntegerField(default=0, verbose_name='Last Debit Note Sequence'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='seq_inv',
            field=models.IntegerField(default=0, verbose_name='Last Invoice Sequence'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='seq_po',
            field=models.IntegerField(default=0, verbose_name='Last Purchase Order Sequence'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='seq_pro',
            field=models.IntegerField(default=0, verbose_name='Last Proforma Invoice Sequence'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='seq_qtn',
            field=models.IntegerField(default=0, verbose_name='Last Quotation Sequence'),
        ),
    ]
