# Generated by Django 4.2.16 on 2026-07-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_companyprofile_admin_backup_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='header_address',
            field=models.TextField(blank=True, help_text='Address text shown in the top-right panel of all printed documents. Use plain text with newlines.', null=True, verbose_name='Document Header Address'),
        ),
    ]
