# Generated by Django 4.2.16 on 2026-08-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_add_gst_enabled_show_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='show_terms',
            field=models.BooleanField(default=True, help_text='When disabled, Terms & Conditions section will not appear on printed documents.', verbose_name='Show Terms & Conditions on Print'),
        ),
    ]
