# Generated by Django 4.2.16 on 2026-06-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_productdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost price / purchase price of the item', max_digits=15),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Trigger low-stock alert when stock falls below this', max_digits=15),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='reason',
            field=models.CharField(blank=True, help_text='Reason for manual adjustment (e.g., damaged, expired)', max_length=255, null=True),
        ),
    ]
