# Generated by Django 5.2.14 on 2026-06-30 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_warranty_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=150)),
                ('invoice_date', models.DateField()),
                ('invoice_amount', models.DecimalField(decimal_places=2, help_text='Total invoice amount including GST', max_digits=15)),
                ('company_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('product_image', models.ImageField(upload_to='warranty/product_images/')),
                ('invoice_document', models.FileField(help_text='PDF or image of the invoice', upload_to='warranty/invoices/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('problem_description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Review', 'In Review'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('attachment_1', models.FileField(blank=True, null=True, upload_to='warranty/claim_attachments/')),
                ('attachment_2', models.FileField(blank=True, null=True, upload_to='warranty/claim_attachments/')),
                ('attachment_3', models.FileField(blank=True, null=True, upload_to='warranty/claim_attachments/')),
                ('product_photo_1', models.ImageField(blank=True, null=True, upload_to='warranty/claim_photos/')),
                ('product_photo_2', models.ImageField(blank=True, null=True, upload_to='warranty/claim_photos/')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='inventory.warrantyregistration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
