# Generated by Django 4.2.16 on 2026-07-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_warrantyregistration_warrantyclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyregistration',
            name='serial_number',
            field=models.TextField(),
        ),
    ]
