# Generated by Django 4.2.16 on 2026-07-03 05:33

from django.db import migrations, models
import tracker.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0032_dual_product_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo_or_document',
            field=models.FileField(blank=True, null=True, upload_to='product_docs/', validators=[tracker.validators.validate_safe_file]),
        ),
        migrations.AlterField(
            model_name='suppliercostoption',
            name='photo_or_document',
            field=models.FileField(blank=True, null=True, upload_to='supplier_quotes/', validators=[tracker.validators.validate_safe_file], verbose_name='Photo or Document'),
        ),
        migrations.AlterField(
            model_name='userreferencedocument',
            name='document',
            field=models.FileField(upload_to='user_references/', validators=[tracker.validators.validate_safe_file]),
        ),
    ]
