# Generated by Django 4.2.16 on 2026-07-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0033_alter_product_photo_or_document_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='productexpense',
                    name='expense_type',
                    field=models.CharField(choices=[('PER_UNIT', 'Per Unit'), ('TOTAL', 'Total Qty')], default='PER_UNIT', max_length=20),
                ),
            ],
            database_operations=[],
        ),
    ]
