# Generated by Django 4.2.16 on 2026-08-21 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0035_orderexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRFQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(help_text='Target supplier name or company', max_length=255)),
                ('supplier_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('supplier_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Quote'), ('SUBMITTED', 'Quote Submitted'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('notes_to_supplier', models.TextField(blank=True, help_text='Instructions, delivery address or terms for the vendor', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('supplier_notes', models.TextField(blank=True, help_text='Vendor comments, payment terms, or remarks', null=True)),
                ('delivery_timeline', models.CharField(blank=True, help_text='Delivery lead time e.g., 2-3 weeks', max_length=150, null=True)),
                ('quote_reference_no', models.CharField(blank=True, help_text='Vendor quotation number', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='tracker.order')),
                ('products', models.ManyToManyField(blank=True, related_name='rfqs', to='tracker.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
